##spring:
##  datasource:
##    url: ${{secrets.DB_URL}}
##    username: ${{secrets.USERNAME}}
##    password: ${{secrets.DB_PASSWORD}}
##    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/twingkling
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: 43.203.234.52
      port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: jjhhh6845
    password: jhjh797913!@



#logging:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.type: trace
